[project]
name = 'Decentralized-Supply-Chain-Risk-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.alert-management]
path = 'contracts/alert-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.entity-verification]
path = 'contracts/entity-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.migration-tracking]
path = 'contracts/migration-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.monitoring]
path = 'contracts/monitoring.clar'
clarity_version = 2
epoch = 2.5

[contracts.risk-assessment]
path = 'contracts/risk-assessment.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
